version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: CICD_DOCKER # has an env var called MY_ENV_VAR

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build -t repo_tp_cicd/cicd_app .
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker image push $DOCKER_USERNAME/cicd_app