version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker ps
            docker build -t cicd_app .
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push cicd_app