version: 2.1

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build -t cicd_app .
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push cicd_app